//go:build go1.22

// Package vtrest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package vtrest

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for TranscodeStatus.
const (
	Completed TranscodeStatus = "completed"
	Failed    TranscodeStatus = "failed"
	Pending   TranscodeStatus = "pending"
	Running   TranscodeStatus = "running"
)

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code string `json:"code"`

	// Message Human-readable error message
	Message string `json:"message"`
}

// TranscodeJob defines model for TranscodeJob.
type TranscodeJob struct {
	// CreatedAt Timestamp when the job was created
	CreatedAt time.Time `json:"createdAt"`

	// DestinationPath Path for the transcoded output file
	DestinationPath string `json:"destinationPath"`

	// Error Error message if the transcode failed
	Error *string `json:"error,omitempty"`

	// Progress Transcoding progress percentage
	Progress int `json:"progress"`

	// SourcePath Path to the source video file
	SourcePath string `json:"sourcePath"`

	// Status Current status of the transcode job
	Status TranscodeStatus `json:"status"`

	// UpdatedAt Timestamp when the job was last updated
	UpdatedAt time.Time `json:"updatedAt"`

	// Uuid Unique identifier for the transcode job
	Uuid openapi_types.UUID `json:"uuid"`
}

// TranscodeRequest defines model for TranscodeRequest.
type TranscodeRequest struct {
	// DestinationPath Path for the transcoded output file
	DestinationPath string `json:"destinationPath"`

	// SourcePath Path to the source video file
	SourcePath string `json:"sourcePath"`

	// Uuid Client-provided UUID for the transcode job
	Uuid openapi_types.UUID `json:"uuid"`
}

// TranscodeStatus Current status of the transcode job
type TranscodeStatus string

// CreateTranscodeJSONRequestBody defines body for CreateTranscode for application/json ContentType.
type CreateTranscodeJSONRequestBody = TranscodeRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// CreateTranscodeWithBody request with any body
	CreateTranscodeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateTranscode(ctx context.Context, body CreateTranscodeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTranscodeStatus request
	GetTranscodeStatus(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) CreateTranscodeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateTranscodeRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateTranscode(ctx context.Context, body CreateTranscodeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateTranscodeRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTranscodeStatus(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTranscodeStatusRequest(c.Server, uuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewCreateTranscodeRequest calls the generic CreateTranscode builder with application/json body
func NewCreateTranscodeRequest(server string, body CreateTranscodeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateTranscodeRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateTranscodeRequestWithBody generates requests for CreateTranscode with any type of body
func NewCreateTranscodeRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/transcodes")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetTranscodeStatusRequest generates requests for GetTranscodeStatus
func NewGetTranscodeStatusRequest(server string, uuid openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "uuid", runtime.ParamLocationPath, uuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/transcodes/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// CreateTranscodeWithBodyWithResponse request with any body
	CreateTranscodeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateTranscodeResponse, error)

	CreateTranscodeWithResponse(ctx context.Context, body CreateTranscodeJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateTranscodeResponse, error)

	// GetTranscodeStatusWithResponse request
	GetTranscodeStatusWithResponse(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetTranscodeStatusResponse, error)
}

type CreateTranscodeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *TranscodeJob
	JSON400      *Error
	JSON409      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r CreateTranscodeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateTranscodeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetTranscodeStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TranscodeJob
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GetTranscodeStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTranscodeStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// CreateTranscodeWithBodyWithResponse request with arbitrary body returning *CreateTranscodeResponse
func (c *ClientWithResponses) CreateTranscodeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateTranscodeResponse, error) {
	rsp, err := c.CreateTranscodeWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateTranscodeResponse(rsp)
}

func (c *ClientWithResponses) CreateTranscodeWithResponse(ctx context.Context, body CreateTranscodeJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateTranscodeResponse, error) {
	rsp, err := c.CreateTranscode(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateTranscodeResponse(rsp)
}

// GetTranscodeStatusWithResponse request returning *GetTranscodeStatusResponse
func (c *ClientWithResponses) GetTranscodeStatusWithResponse(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetTranscodeStatusResponse, error) {
	rsp, err := c.GetTranscodeStatus(ctx, uuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTranscodeStatusResponse(rsp)
}

// ParseCreateTranscodeResponse parses an HTTP response from a CreateTranscodeWithResponse call
func ParseCreateTranscodeResponse(rsp *http.Response) (*CreateTranscodeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateTranscodeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest TranscodeJob
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetTranscodeStatusResponse parses an HTTP response from a GetTranscodeStatusWithResponse call
func ParseGetTranscodeStatusResponse(rsp *http.Response) (*GetTranscodeStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTranscodeStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TranscodeJob
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Start a new transcode job
	// (POST /transcodes)
	CreateTranscode(w http.ResponseWriter, r *http.Request)
	// Get transcode job status
	// (GET /transcodes/{uuid})
	GetTranscodeStatus(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateTranscode operation middleware
func (siw *ServerInterfaceWrapper) CreateTranscode(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTranscode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTranscodeStatus operation middleware
func (siw *ServerInterfaceWrapper) GetTranscodeStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTranscodeStatus(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/transcodes", wrapper.CreateTranscode)
	m.HandleFunc("GET "+options.BaseURL+"/transcodes/{uuid}", wrapper.GetTranscodeStatus)

	return m
}

type CreateTranscodeRequestObject struct {
	Body *CreateTranscodeJSONRequestBody
}

type CreateTranscodeResponseObject interface {
	VisitCreateTranscodeResponse(w http.ResponseWriter) error
}

type CreateTranscode201JSONResponse TranscodeJob

func (response CreateTranscode201JSONResponse) VisitCreateTranscodeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateTranscode400JSONResponse Error

func (response CreateTranscode400JSONResponse) VisitCreateTranscodeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateTranscode409JSONResponse Error

func (response CreateTranscode409JSONResponse) VisitCreateTranscodeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateTranscode500JSONResponse Error

func (response CreateTranscode500JSONResponse) VisitCreateTranscodeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetTranscodeStatusRequestObject struct {
	Uuid openapi_types.UUID `json:"uuid"`
}

type GetTranscodeStatusResponseObject interface {
	VisitGetTranscodeStatusResponse(w http.ResponseWriter) error
}

type GetTranscodeStatus200JSONResponse TranscodeJob

func (response GetTranscodeStatus200JSONResponse) VisitGetTranscodeStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTranscodeStatus404JSONResponse Error

func (response GetTranscodeStatus404JSONResponse) VisitGetTranscodeStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetTranscodeStatus500JSONResponse Error

func (response GetTranscodeStatus500JSONResponse) VisitGetTranscodeStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Start a new transcode job
	// (POST /transcodes)
	CreateTranscode(ctx context.Context, request CreateTranscodeRequestObject) (CreateTranscodeResponseObject, error)
	// Get transcode job status
	// (GET /transcodes/{uuid})
	GetTranscodeStatus(ctx context.Context, request GetTranscodeStatusRequestObject) (GetTranscodeStatusResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateTranscode operation middleware
func (sh *strictHandler) CreateTranscode(w http.ResponseWriter, r *http.Request) {
	var request CreateTranscodeRequestObject

	var body CreateTranscodeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTranscode(ctx, request.(CreateTranscodeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTranscode")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateTranscodeResponseObject); ok {
		if err := validResponse.VisitCreateTranscodeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTranscodeStatus operation middleware
func (sh *strictHandler) GetTranscodeStatus(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request GetTranscodeStatusRequestObject

	request.Uuid = uuid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTranscodeStatus(ctx, request.(GetTranscodeStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTranscodeStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTranscodeStatusResponseObject); ok {
		if err := validResponse.VisitGetTranscodeStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xW3W7bOBN9FYLfdylHSlZJU91l26DrRbHI5qc3QVDQ4shiIP6EHDoxAr/7gqTs2JGS",
	"Ft10d68sS8M5w5lzDvlIay2NVqDQ0eqRuroFyeLjqbXahgdjtQGLAuLrWnMIvxxcbYVBoRWtUjCJ3zIK",
	"D0yaDmhFp398Ofk8/fj1/PTPq9OLS5pRXJrwwaEVak5XGZXgHJuPpPzNS6YmFhhnsw4IRIR19DbIZQvE",
	"aW9rIIZhS4QjQi1YJ/gQb5VRC3deWOC0uqZ9weusN5t4PbuFGkN9l5YpF+J+17ORblhgCPwEh/VfCgkO",
	"mTTkvgVFsAVyq2fknjnSr6IZbbSVDGlFOUOYoJAw1iMODoViIfEZw3aIFd6SRtuIguuKOdEejUfSiG40",
	"L6xHPDbMvilENLtZScNEB3wsn7F6bsG5kWb0q4Wak3UUMWBrUJjmKdmDkF7Sar8oMiqFSv+KDYxQCHOw",
	"ASdN+5VWoI4196xYCA76xSY4ZOhjyf+30NCK/i9/0kTeCyLf0OAiha8y6g3/gdl3zCHpl343AbwXfIhy",
	"pcSdByI4KBSNADukQIDdRomJvqWKPqhvzE67h1zcmnq2JYft9rwqq3O48+BwKK03Iv2TT+SRBy5P33Op",
	"FwK+vjsozJ405Sgz/gbNhrBCbVBfAhwf84dOgMKJsTpk4uTqavrxxUk/4R4eFnBcFsUEDt7PJuU+Lyfs",
	"3f7RpCyPjg4Py7IoiuKHqfEaI14d98VGbc826a0FhSSRjuhmfHcqeMI1NaCCldCMWq9Uegqi7aBXVbKo",
	"m+F2VhkVqtHDAk7OprGpkik2DzaVxolbxnWrZ4HkKDA2+EsM2OzMkpOzKc3oAqxLKff3ir0i7F4bUMwI",
	"WtFf4quMhoMqdiHfbDH+NdqN2MmHKCtHGFFwP14YuRfYEkbql8giOEijEVS9pLEiGyc25Zv8m53QNHNw",
	"+Kvmy3ToKwQVK2PGdKKOa/NbF8pb3xq+20LXkl/tsguth/jCGa1c6sdBsf/2+OEkj9jjZ1Ty6t7KiPN1",
	"Dc41vuuWYZZlUbxZRemKNVLKNN1fiF13KuC+//m4J7uKS6TCVrjEI9aF69iSwINwGM/Aw3+mGwhWsY44",
	"sAuw6SoYrcl5KZld0opeILPYC2TXNULclsryx+Bhq1DMHEa0dg7orXLRfuqBKbGBJe0q6RPgc6sLYrdM",
	"AoJ1tLoeXBVaSM19wfJECDLJaRWT8OTUu8rJtrr8LU+/Gais+JdU5ja3qbIofz6TdsGVRtJor/h/ismf",
	"AJ+pcN2kGBcXjhHps65ZRzgsoNNGRtrG2HAVsx2taItoqjzvQlyrHVbHxXFBVzervwIAAP//VddKjgUO",
	"AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
